// Code generated by stanc v2.33.1
#include <stan/model/model_header.hpp>
namespace hierarchical_probit_bandit_model_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 86> locations_array__ =
  {" (found before start of program)",
  " (in 'hierarchical_probit_bandit.stan', line 47, column 2 to column 26)",
  " (in 'hierarchical_probit_bandit.stan', line 48, column 2 to column 27)",
  " (in 'hierarchical_probit_bandit.stan', line 49, column 2 to column 28)",
  " (in 'hierarchical_probit_bandit.stan', line 51, column 2 to column 20)",
  " (in 'hierarchical_probit_bandit.stan', line 55, column 2 to column 29)",
  " (in 'hierarchical_probit_bandit.stan', line 56, column 2 to column 16)",
  " (in 'hierarchical_probit_bandit.stan', line 57, column 2 to column 29)",
  " (in 'hierarchical_probit_bandit.stan', line 58, column 2 to column 29)",
  " (in 'hierarchical_probit_bandit.stan', line 113, column 2 to column 19)",
  " (in 'hierarchical_probit_bandit.stan', line 114, column 2 to column 20)",
  " (in 'hierarchical_probit_bandit.stan', line 61, column 4 to column 57)",
  " (in 'hierarchical_probit_bandit.stan', line 62, column 4 to column 33)",
  " (in 'hierarchical_probit_bandit.stan', line 60, column 17 to line 63, column 3)",
  " (in 'hierarchical_probit_bandit.stan', line 60, column 2 to line 63, column 3)",
  " (in 'hierarchical_probit_bandit.stan', line 68, column 11 to column 12)",
  " (in 'hierarchical_probit_bandit.stan', line 68, column 14 to column 15)",
  " (in 'hierarchical_probit_bandit.stan', line 68, column 4 to column 21)",
  " (in 'hierarchical_probit_bandit.stan', line 71, column 8 to column 46)",
  " (in 'hierarchical_probit_bandit.stan', line 70, column 22 to line 72, column 7)",
  " (in 'hierarchical_probit_bandit.stan', line 70, column 6 to line 72, column 7)",
  " (in 'hierarchical_probit_bandit.stan', line 69, column 19 to line 73, column 5)",
  " (in 'hierarchical_probit_bandit.stan', line 69, column 4 to line 73, column 5)",
  " (in 'hierarchical_probit_bandit.stan', line 74, column 11 to column 12)",
  " (in 'hierarchical_probit_bandit.stan', line 74, column 14 to column 15)",
  " (in 'hierarchical_probit_bandit.stan', line 74, column 4 to column 47)",
  " (in 'hierarchical_probit_bandit.stan', line 77, column 6 to column 61)",
  " (in 'hierarchical_probit_bandit.stan', line 76, column 20 to line 78, column 5)",
  " (in 'hierarchical_probit_bandit.stan', line 76, column 4 to line 78, column 5)",
  " (in 'hierarchical_probit_bandit.stan', line 67, column 17 to line 79, column 3)",
  " (in 'hierarchical_probit_bandit.stan', line 67, column 2 to line 79, column 3)",
  " (in 'hierarchical_probit_bandit.stan', line 116, column 4 to column 20)",
  " (in 'hierarchical_probit_bandit.stan', line 117, column 4 to column 21)",
  " (in 'hierarchical_probit_bandit.stan', line 118, column 4 to column 46)",
  " (in 'hierarchical_probit_bandit.stan', line 119, column 4 to column 26)",
  " (in 'hierarchical_probit_bandit.stan', line 120, column 4 to column 49)",
  " (in 'hierarchical_probit_bandit.stan', line 115, column 17 to line 121, column 3)",
  " (in 'hierarchical_probit_bandit.stan', line 115, column 2 to line 121, column 3)",
  " (in 'hierarchical_probit_bandit.stan', line 86, column 6 to column 30)",
  " (in 'hierarchical_probit_bandit.stan', line 85, column 20 to line 87, column 5)",
  " (in 'hierarchical_probit_bandit.stan', line 85, column 4 to line 87, column 5)",
  " (in 'hierarchical_probit_bandit.stan', line 84, column 17 to line 88, column 3)",
  " (in 'hierarchical_probit_bandit.stan', line 84, column 2 to line 88, column 3)",
  " (in 'hierarchical_probit_bandit.stan', line 92, column 4 to column 42)",
  " (in 'hierarchical_probit_bandit.stan', line 93, column 4 to column 40)",
  " (in 'hierarchical_probit_bandit.stan', line 91, column 17 to line 94, column 3)",
  " (in 'hierarchical_probit_bandit.stan', line 91, column 2 to line 94, column 3)",
  " (in 'hierarchical_probit_bandit.stan', line 100, column 4 to column 49)",
  " (in 'hierarchical_probit_bandit.stan', line 99, column 17 to line 101, column 3)",
  " (in 'hierarchical_probit_bandit.stan', line 99, column 2 to line 101, column 3)",
  " (in 'hierarchical_probit_bandit.stan', line 105, column 4 to column 20)",
  " (in 'hierarchical_probit_bandit.stan', line 106, column 4 to column 21)",
  " (in 'hierarchical_probit_bandit.stan', line 107, column 4 to column 46)",
  " (in 'hierarchical_probit_bandit.stan', line 108, column 4 to column 31)",
  " (in 'hierarchical_probit_bandit.stan', line 104, column 17 to line 109, column 3)",
  " (in 'hierarchical_probit_bandit.stan', line 104, column 2 to line 109, column 3)",
  " (in 'hierarchical_probit_bandit.stan', line 30, column 2 to column 17)",
  " (in 'hierarchical_probit_bandit.stan', line 31, column 2 to column 17)",
  " (in 'hierarchical_probit_bandit.stan', line 32, column 2 to column 17)",
  " (in 'hierarchical_probit_bandit.stan', line 33, column 2 to column 17)",
  " (in 'hierarchical_probit_bandit.stan', line 35, column 9 to column 10)",
  " (in 'hierarchical_probit_bandit.stan', line 35, column 12 to column 13)",
  " (in 'hierarchical_probit_bandit.stan', line 35, column 2 to column 17)",
  " (in 'hierarchical_probit_bandit.stan', line 36, column 8 to column 9)",
  " (in 'hierarchical_probit_bandit.stan', line 36, column 2 to column 37)",
  " (in 'hierarchical_probit_bandit.stan', line 37, column 8 to column 9)",
  " (in 'hierarchical_probit_bandit.stan', line 37, column 2 to column 38)",
  " (in 'hierarchical_probit_bandit.stan', line 38, column 8 to column 9)",
  " (in 'hierarchical_probit_bandit.stan', line 38, column 2 to column 35)",
  " (in 'hierarchical_probit_bandit.stan', line 40, column 2 to column 20)",
  " (in 'hierarchical_probit_bandit.stan', line 41, column 2 to column 22)",
  " (in 'hierarchical_probit_bandit.stan', line 42, column 2 to column 22)",
  " (in 'hierarchical_probit_bandit.stan', line 47, column 8 to column 9)",
  " (in 'hierarchical_probit_bandit.stan', line 47, column 11 to column 12)",
  " (in 'hierarchical_probit_bandit.stan', line 47, column 21 to column 22)",
  " (in 'hierarchical_probit_bandit.stan', line 48, column 8 to column 9)",
  " (in 'hierarchical_probit_bandit.stan', line 48, column 18 to column 19)",
  " (in 'hierarchical_probit_bandit.stan', line 49, column 18 to column 19)",
  " (in 'hierarchical_probit_bandit.stan', line 51, column 9 to column 10)",
  " (in 'hierarchical_probit_bandit.stan', line 56, column 9 to column 10)",
  " (in 'hierarchical_probit_bandit.stan', line 57, column 18 to column 19)",
  " (in 'hierarchical_probit_bandit.stan', line 58, column 8 to column 9)",
  " (in 'hierarchical_probit_bandit.stan', line 58, column 11 to column 12)",
  " (in 'hierarchical_probit_bandit.stan', line 58, column 21 to column 22)",
  " (in 'hierarchical_probit_bandit.stan', line 113, column 9 to column 10)",
  " (in 'hierarchical_probit_bandit.stan', line 114, column 9 to column 10)"};
class hierarchical_probit_bandit_model final : public model_base_crtp<hierarchical_probit_bandit_model> {
 private:
  int T;
  int K;
  int N;
  int P;
  Eigen::Matrix<double,-1,-1> X_data__;
  std::vector<int> arm;
  std::vector<int> task;
  std::vector<int> Y;
  double lam;
  double a_sig;
  double b_sig;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
 public:
  ~hierarchical_probit_bandit_model() {}
  hierarchical_probit_bandit_model(stan::io::var_context& context__,
                                   unsigned int random_seed__ = 0,
                                   std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "hierarchical_probit_bandit_model_namespace::hierarchical_probit_bandit_model";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 56;
      context__.validate_dims("data initialization", "T", "int",
        std::vector<size_t>{});
      T = std::numeric_limits<int>::min();
      current_statement__ = 56;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 56;
      stan::math::check_greater_or_equal(function__, "T", T, 1);
      current_statement__ = 57;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 57;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 57;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 58;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 58;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 58;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 59;
      context__.validate_dims("data initialization", "P", "int",
        std::vector<size_t>{});
      P = std::numeric_limits<int>::min();
      current_statement__ = 59;
      P = context__.vals_i("P")[(1 - 1)];
      current_statement__ = 59;
      stan::math::check_greater_or_equal(function__, "P", P, 1);
      current_statement__ = 60;
      stan::math::validate_non_negative_index("X", "T", T);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("X", "P", P);
      current_statement__ = 62;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(T), static_cast<size_t>(P)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(T, P,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(), T, P);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 62;
        X_flat__ = context__.vals_r("X");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 63;
      stan::math::validate_non_negative_index("arm", "T", T);
      current_statement__ = 64;
      context__.validate_dims("data initialization", "arm", "int",
        std::vector<size_t>{static_cast<size_t>(T)});
      arm = std::vector<int>(T, std::numeric_limits<int>::min());
      current_statement__ = 64;
      arm = context__.vals_i("arm");
      current_statement__ = 64;
      stan::math::check_greater_or_equal(function__, "arm", arm, 1);
      current_statement__ = 64;
      stan::math::check_less_or_equal(function__, "arm", arm, K);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("task", "T", T);
      current_statement__ = 66;
      context__.validate_dims("data initialization", "task", "int",
        std::vector<size_t>{static_cast<size_t>(T)});
      task = std::vector<int>(T, std::numeric_limits<int>::min());
      current_statement__ = 66;
      task = context__.vals_i("task");
      current_statement__ = 66;
      stan::math::check_greater_or_equal(function__, "task", task, 1);
      current_statement__ = 66;
      stan::math::check_less_or_equal(function__, "task", task, N);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("Y", "T", T);
      current_statement__ = 68;
      context__.validate_dims("data initialization", "Y", "int",
        std::vector<size_t>{static_cast<size_t>(T)});
      Y = std::vector<int>(T, std::numeric_limits<int>::min());
      current_statement__ = 68;
      Y = context__.vals_i("Y");
      current_statement__ = 68;
      stan::math::check_greater_or_equal(function__, "Y", Y, 0);
      current_statement__ = 68;
      stan::math::check_less_or_equal(function__, "Y", Y, 1);
      current_statement__ = 69;
      context__.validate_dims("data initialization", "lam", "double",
        std::vector<size_t>{});
      lam = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 69;
      lam = context__.vals_r("lam")[(1 - 1)];
      current_statement__ = 69;
      stan::math::check_greater_or_equal(function__, "lam", lam, 0);
      current_statement__ = 70;
      context__.validate_dims("data initialization", "a_sig", "double",
        std::vector<size_t>{});
      a_sig = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 70;
      a_sig = context__.vals_r("a_sig")[(1 - 1)];
      current_statement__ = 70;
      stan::math::check_greater_or_equal(function__, "a_sig", a_sig, 0);
      current_statement__ = 71;
      context__.validate_dims("data initialization", "b_sig", "double",
        std::vector<size_t>{});
      b_sig = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 71;
      b_sig = context__.vals_r("b_sig")[(1 - 1)];
      current_statement__ = 71;
      stan::math::check_greater_or_equal(function__, "b_sig", b_sig, 0);
      current_statement__ = 72;
      stan::math::validate_non_negative_index("z", "K", K);
      current_statement__ = 73;
      stan::math::validate_non_negative_index("z", "N", N);
      current_statement__ = 74;
      stan::math::validate_non_negative_index("z", "P", P);
      current_statement__ = 75;
      stan::math::validate_non_negative_index("beta0", "K", K);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("beta0", "P", P);
      current_statement__ = 77;
      stan::math::validate_non_negative_index("sigma2", "K", K);
      current_statement__ = 78;
      stan::math::validate_non_negative_index("rho_raw", "K", K);
      current_statement__ = 79;
      stan::math::validate_non_negative_index("rho", "K", K);
      current_statement__ = 80;
      stan::math::validate_non_negative_index("sigma_k", "K", K);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("beta", "K", K);
      current_statement__ = 82;
      stan::math::validate_non_negative_index("beta", "N", N);
      current_statement__ = 83;
      stan::math::validate_non_negative_index("beta", "P", P);
      current_statement__ = 84;
      stan::math::validate_non_negative_index("p_pred", "T", T);
      current_statement__ = 85;
      stan::math::validate_non_negative_index("log_lik", "T", T);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = (K * (N * P)) + (K * P) + K + K;
  }
  inline std::string model_name() const final {
    return "hierarchical_probit_bandit_model";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.33.1",
             "stancflags = --filename-in-msg=hierarchical_probit_bandit.stan"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "hierarchical_probit_bandit_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>> z =
        std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(K,
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(N,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__)));
      current_statement__ = 1;
      z = in__.template read<
            std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>>(K,
            N, P);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> beta0 =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(K,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__));
      current_statement__ = 2;
      beta0 = in__.template read<
                std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(K, P);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 3;
      sigma2 = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                 K);
      Eigen::Matrix<local_scalar_t__,-1,1> rho_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 4;
      rho_raw = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      local_scalar_t__ lo = DUMMY_VAR__;
      current_statement__ = 5;
      lo = (-(1.0) / (P - 1.0));
      Eigen::Matrix<local_scalar_t__,-1,1> rho =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma_k =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>> beta =
        std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(K,
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(N,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__)));
      current_statement__ = 14;
      for (int k = 1; k <= K; ++k) {
        current_statement__ = 11;
        stan::model::assign(rho, (lo + ((1.0 - lo) *
          stan::math::inv_logit(
            stan::model::rvalue(rho_raw, "rho_raw", stan::model::index_uni(k))))),
          "assigning variable rho", stan::model::index_uni(k));
        current_statement__ = 12;
        stan::model::assign(sigma_k,
          stan::math::sqrt(
            stan::model::rvalue(sigma2, "sigma2", stan::model::index_uni(k))),
          "assigning variable sigma_k", stan::model::index_uni(k));
      }
      current_statement__ = 30;
      for (int k = 1; k <= K; ++k) {
        current_statement__ = 15;
        stan::math::validate_non_negative_index("R_k", "P", P);
        current_statement__ = 16;
        stan::math::validate_non_negative_index("R_k", "P", P);
        Eigen::Matrix<local_scalar_t__,-1,-1> R_k =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(P, P, DUMMY_VAR__);
        current_statement__ = 22;
        for (int i = 1; i <= P; ++i) {
          current_statement__ = 20;
          for (int j_ = 1; j_ <= P; ++j_) {
            current_statement__ = 18;
            stan::model::assign(R_k,
              (stan::math::logical_eq(i, j_) ? 1.0 : stan::model::rvalue(rho,
                                                       "rho",
                                                       stan::model::index_uni(
                                                         k))),
              "assigning variable R_k", stan::model::index_uni(i),
              stan::model::index_uni(j_));
          }
        }
        current_statement__ = 23;
        stan::math::validate_non_negative_index("L_k", "P", P);
        current_statement__ = 24;
        stan::math::validate_non_negative_index("L_k", "P", P);
        Eigen::Matrix<local_scalar_t__,-1,-1> L_k =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(P, P, DUMMY_VAR__);
        current_statement__ = 25;
        stan::model::assign(L_k, stan::math::cholesky_decompose(R_k),
          "assigning variable L_k");
        current_statement__ = 28;
        for (int j_ = 1; j_ <= N; ++j_) {
          current_statement__ = 26;
          stan::model::assign(beta,
            stan::math::add(
              stan::model::rvalue(beta0, "beta0", stan::model::index_uni(k)),
              stan::math::multiply(
                stan::model::rvalue(sigma_k, "sigma_k",
                  stan::model::index_uni(k)),
                stan::math::multiply(L_k,
                  stan::model::rvalue(z, "z", stan::model::index_uni(k),
                    stan::model::index_uni(j_))))),
            "assigning variable beta", stan::model::index_uni(k),
            stan::model::index_uni(j_));
        }
      }
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "sigma_k", sigma_k, 0);
      {
        current_statement__ = 42;
        for (int k = 1; k <= K; ++k) {
          current_statement__ = 40;
          for (int j_ = 1; j_ <= N; ++j_) {
            current_statement__ = 38;
            lp_accum__.add(stan::math::std_normal_lpdf<propto__>(
                             stan::model::rvalue(z, "z",
                               stan::model::index_uni(k),
                               stan::model::index_uni(j_))));
          }
        }
        current_statement__ = 46;
        for (int k = 1; k <= K; ++k) {
          current_statement__ = 43;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(beta0, "beta0",
                             stan::model::index_uni(k)), 0, (1.0 /
                           stan::math::sqrt(lam))));
          current_statement__ = 44;
          lp_accum__.add(stan::math::inv_gamma_lpdf<propto__>(
                           stan::model::rvalue(sigma2, "sigma2",
                             stan::model::index_uni(k)), a_sig, b_sig));
        }
        current_statement__ = 49;
        for (int k = 1; k <= K; ++k) {
          current_statement__ = 47;
          lp_accum__.add((stan::math::log(
                            (stan::model::rvalue(rho, "rho",
                               stan::model::index_uni(k)) - lo)) +
            stan::math::log((1 -
              stan::model::rvalue(rho, "rho", stan::model::index_uni(k))))));
        }
        current_statement__ = 55;
        for (int t = 1; t <= T; ++t) {
          int k = std::numeric_limits<int>::min();
          current_statement__ = 50;
          k = stan::model::rvalue(arm, "arm", stan::model::index_uni(t));
          int j_ = std::numeric_limits<int>::min();
          current_statement__ = 51;
          j_ = stan::model::rvalue(task, "task", stan::model::index_uni(t));
          local_scalar_t__ eta = DUMMY_VAR__;
          current_statement__ = 52;
          eta = stan::math::dot_product(
                  stan::model::rvalue(X, "X", stan::model::index_uni(t)),
                  stan::model::rvalue(beta, "beta",
                    stan::model::index_uni(k), stan::model::index_uni(j_)));
          current_statement__ = 53;
          lp_accum__.add(stan::math::bernoulli_lpmf<propto__>(
                           stan::model::rvalue(Y, "Y",
                             stan::model::index_uni(t)), stan::math::Phi(eta)));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "hierarchical_probit_bandit_model_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>> z =
        std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(K,
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(N,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__)));
      current_statement__ = 1;
      z = in__.template read<
            std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>>(K,
            N, P);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> beta0 =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(K,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__));
      current_statement__ = 2;
      beta0 = in__.template read<
                std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(K, P);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 3;
      sigma2 = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                 K);
      Eigen::Matrix<local_scalar_t__,-1,1> rho_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 4;
      rho_raw = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      local_scalar_t__ lo = DUMMY_VAR__;
      current_statement__ = 5;
      lo = (-(1.0) / (P - 1.0));
      Eigen::Matrix<local_scalar_t__,-1,1> rho =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma_k =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>> beta =
        std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(K,
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(N,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__)));
      current_statement__ = 14;
      for (int k = 1; k <= K; ++k) {
        current_statement__ = 11;
        stan::model::assign(rho, (lo + ((1.0 - lo) *
          stan::math::inv_logit(
            stan::model::rvalue(rho_raw, "rho_raw", stan::model::index_uni(k))))),
          "assigning variable rho", stan::model::index_uni(k));
        current_statement__ = 12;
        stan::model::assign(sigma_k,
          stan::math::sqrt(
            stan::model::rvalue(sigma2, "sigma2", stan::model::index_uni(k))),
          "assigning variable sigma_k", stan::model::index_uni(k));
      }
      current_statement__ = 30;
      for (int k = 1; k <= K; ++k) {
        current_statement__ = 15;
        stan::math::validate_non_negative_index("R_k", "P", P);
        current_statement__ = 16;
        stan::math::validate_non_negative_index("R_k", "P", P);
        Eigen::Matrix<local_scalar_t__,-1,-1> R_k =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(P, P, DUMMY_VAR__);
        current_statement__ = 22;
        for (int i = 1; i <= P; ++i) {
          current_statement__ = 20;
          for (int j_ = 1; j_ <= P; ++j_) {
            current_statement__ = 18;
            stan::model::assign(R_k,
              (stan::math::logical_eq(i, j_) ? 1.0 : stan::model::rvalue(rho,
                                                       "rho",
                                                       stan::model::index_uni(
                                                         k))),
              "assigning variable R_k", stan::model::index_uni(i),
              stan::model::index_uni(j_));
          }
        }
        current_statement__ = 23;
        stan::math::validate_non_negative_index("L_k", "P", P);
        current_statement__ = 24;
        stan::math::validate_non_negative_index("L_k", "P", P);
        Eigen::Matrix<local_scalar_t__,-1,-1> L_k =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(P, P, DUMMY_VAR__);
        current_statement__ = 25;
        stan::model::assign(L_k, stan::math::cholesky_decompose(R_k),
          "assigning variable L_k");
        current_statement__ = 28;
        for (int j_ = 1; j_ <= N; ++j_) {
          current_statement__ = 26;
          stan::model::assign(beta,
            stan::math::add(
              stan::model::rvalue(beta0, "beta0", stan::model::index_uni(k)),
              stan::math::multiply(
                stan::model::rvalue(sigma_k, "sigma_k",
                  stan::model::index_uni(k)),
                stan::math::multiply(L_k,
                  stan::model::rvalue(z, "z", stan::model::index_uni(k),
                    stan::model::index_uni(j_))))),
            "assigning variable beta", stan::model::index_uni(k),
            stan::model::index_uni(j_));
        }
      }
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "sigma_k", sigma_k, 0);
      {
        current_statement__ = 42;
        for (int k = 1; k <= K; ++k) {
          current_statement__ = 40;
          for (int j_ = 1; j_ <= N; ++j_) {
            current_statement__ = 38;
            lp_accum__.add(stan::math::std_normal_lpdf<propto__>(
                             stan::model::rvalue(z, "z",
                               stan::model::index_uni(k),
                               stan::model::index_uni(j_))));
          }
        }
        current_statement__ = 46;
        for (int k = 1; k <= K; ++k) {
          current_statement__ = 43;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(beta0, "beta0",
                             stan::model::index_uni(k)), 0, (1.0 /
                           stan::math::sqrt(lam))));
          current_statement__ = 44;
          lp_accum__.add(stan::math::inv_gamma_lpdf<propto__>(
                           stan::model::rvalue(sigma2, "sigma2",
                             stan::model::index_uni(k)), a_sig, b_sig));
        }
        current_statement__ = 49;
        for (int k = 1; k <= K; ++k) {
          current_statement__ = 47;
          lp_accum__.add((stan::math::log(
                            (stan::model::rvalue(rho, "rho",
                               stan::model::index_uni(k)) - lo)) +
            stan::math::log((1 -
              stan::model::rvalue(rho, "rho", stan::model::index_uni(k))))));
        }
        current_statement__ = 55;
        for (int t = 1; t <= T; ++t) {
          int k = std::numeric_limits<int>::min();
          current_statement__ = 50;
          k = stan::model::rvalue(arm, "arm", stan::model::index_uni(t));
          int j_ = std::numeric_limits<int>::min();
          current_statement__ = 51;
          j_ = stan::model::rvalue(task, "task", stan::model::index_uni(t));
          local_scalar_t__ eta = DUMMY_VAR__;
          current_statement__ = 52;
          eta = stan::math::dot_product(
                  stan::model::rvalue(X, "X", stan::model::index_uni(t)),
                  stan::model::rvalue(beta, "beta",
                    stan::model::index_uni(k), stan::model::index_uni(j_)));
          current_statement__ = 53;
          lp_accum__.add(stan::math::bernoulli_lpmf<propto__>(
                           stan::model::rvalue(Y, "Y",
                             stan::model::index_uni(t)), stan::math::Phi(eta)));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "hierarchical_probit_bandit_model_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      std::vector<std::vector<Eigen::Matrix<double,-1,1>>> z =
        std::vector<std::vector<Eigen::Matrix<double,-1,1>>>(K,
          std::vector<Eigen::Matrix<double,-1,1>>(N,
            Eigen::Matrix<double,-1,1>::Constant(P,
              std::numeric_limits<double>::quiet_NaN())));
      current_statement__ = 1;
      z = in__.template read<
            std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>>(K,
            N, P);
      std::vector<Eigen::Matrix<double,-1,1>> beta0 =
        std::vector<Eigen::Matrix<double,-1,1>>(K,
          Eigen::Matrix<double,-1,1>::Constant(P,
            std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 2;
      beta0 = in__.template read<
                std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(K, P);
      Eigen::Matrix<double,-1,1> sigma2 =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      sigma2 = in__.template read_constrain_lb<
                 Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__,
                 K);
      Eigen::Matrix<double,-1,1> rho_raw =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      rho_raw = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(K);
      double lo = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double,-1,1> rho =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> sigma_k =
        Eigen::Matrix<double,-1,1>::Constant(K,
          std::numeric_limits<double>::quiet_NaN());
      std::vector<std::vector<Eigen::Matrix<double,-1,1>>> beta =
        std::vector<std::vector<Eigen::Matrix<double,-1,1>>>(K,
          std::vector<Eigen::Matrix<double,-1,1>>(N,
            Eigen::Matrix<double,-1,1>::Constant(P,
              std::numeric_limits<double>::quiet_NaN())));
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= K; ++sym3__) {
            out__.write(z[(sym3__ - 1)][(sym2__ - 1)][(sym1__ - 1)]);
          }
        }
      }
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          out__.write(beta0[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      out__.write(sigma2);
      out__.write(rho_raw);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 5;
      lo = (-(1.0) / (P - 1.0));
      current_statement__ = 14;
      for (int k = 1; k <= K; ++k) {
        current_statement__ = 11;
        stan::model::assign(rho, (lo + ((1.0 - lo) *
          stan::math::inv_logit(
            stan::model::rvalue(rho_raw, "rho_raw", stan::model::index_uni(k))))),
          "assigning variable rho", stan::model::index_uni(k));
        current_statement__ = 12;
        stan::model::assign(sigma_k,
          stan::math::sqrt(
            stan::model::rvalue(sigma2, "sigma2", stan::model::index_uni(k))),
          "assigning variable sigma_k", stan::model::index_uni(k));
      }
      current_statement__ = 30;
      for (int k = 1; k <= K; ++k) {
        current_statement__ = 15;
        stan::math::validate_non_negative_index("R_k", "P", P);
        current_statement__ = 16;
        stan::math::validate_non_negative_index("R_k", "P", P);
        Eigen::Matrix<double,-1,-1> R_k =
          Eigen::Matrix<double,-1,-1>::Constant(P, P,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 22;
        for (int i = 1; i <= P; ++i) {
          current_statement__ = 20;
          for (int j_ = 1; j_ <= P; ++j_) {
            current_statement__ = 18;
            stan::model::assign(R_k,
              (stan::math::logical_eq(i, j_) ? 1.0 : stan::model::rvalue(rho,
                                                       "rho",
                                                       stan::model::index_uni(
                                                         k))),
              "assigning variable R_k", stan::model::index_uni(i),
              stan::model::index_uni(j_));
          }
        }
        current_statement__ = 23;
        stan::math::validate_non_negative_index("L_k", "P", P);
        current_statement__ = 24;
        stan::math::validate_non_negative_index("L_k", "P", P);
        Eigen::Matrix<double,-1,-1> L_k =
          Eigen::Matrix<double,-1,-1>::Constant(P, P,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 25;
        stan::model::assign(L_k, stan::math::cholesky_decompose(R_k),
          "assigning variable L_k");
        current_statement__ = 28;
        for (int j_ = 1; j_ <= N; ++j_) {
          current_statement__ = 26;
          stan::model::assign(beta,
            stan::math::add(
              stan::model::rvalue(beta0, "beta0", stan::model::index_uni(k)),
              stan::math::multiply(
                stan::model::rvalue(sigma_k, "sigma_k",
                  stan::model::index_uni(k)),
                stan::math::multiply(L_k,
                  stan::model::rvalue(z, "z", stan::model::index_uni(k),
                    stan::model::index_uni(j_))))),
            "assigning variable beta", stan::model::index_uni(k),
            stan::model::index_uni(j_));
        }
      }
      current_statement__ = 7;
      stan::math::check_greater_or_equal(function__, "sigma_k", sigma_k, 0);
      if (emit_transformed_parameters__) {
        out__.write(lo);
        out__.write(rho);
        out__.write(sigma_k);
        current_statement__ = 8;
        for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= K; ++sym3__) {
              out__.write(beta[(sym3__ - 1)][(sym2__ - 1)][(sym1__ - 1)]);
            }
          }
        }
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> p_pred =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double,-1,1> log_lik =
        Eigen::Matrix<double,-1,1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 37;
      for (int t = 1; t <= T; ++t) {
        int k = std::numeric_limits<int>::min();
        current_statement__ = 31;
        k = stan::model::rvalue(arm, "arm", stan::model::index_uni(t));
        int j_ = std::numeric_limits<int>::min();
        current_statement__ = 32;
        j_ = stan::model::rvalue(task, "task", stan::model::index_uni(t));
        double eta = std::numeric_limits<double>::quiet_NaN();
        current_statement__ = 33;
        eta = stan::math::dot_product(
                stan::model::rvalue(X, "X", stan::model::index_uni(t)),
                stan::model::rvalue(beta, "beta", stan::model::index_uni(k),
                  stan::model::index_uni(j_)));
        current_statement__ = 34;
        stan::model::assign(p_pred, stan::math::Phi(eta),
          "assigning variable p_pred", stan::model::index_uni(t));
        current_statement__ = 35;
        stan::model::assign(log_lik,
          stan::math::bernoulli_lpmf<false>(
            stan::model::rvalue(Y, "Y", stan::model::index_uni(t)),
            stan::math::Phi(eta)), "assigning variable log_lik",
          stan::model::index_uni(t));
      }
      out__.write(p_pred);
      out__.write(log_lik);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>> z =
        std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(K,
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(N,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__)));
      current_statement__ = 1;
      for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= K; ++sym3__) {
            current_statement__ = 1;
            stan::model::assign(z, in__.read<local_scalar_t__>(),
              "assigning variable z", stan::model::index_uni(sym3__),
              stan::model::index_uni(sym2__), stan::model::index_uni(sym1__));
          }
        }
      }
      out__.write(z);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> beta0 =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(K,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__));
      current_statement__ = 2;
      for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
          current_statement__ = 2;
          stan::model::assign(beta0, in__.read<local_scalar_t__>(),
            "assigning variable beta0", stan::model::index_uni(sym2__),
            stan::model::index_uni(sym1__));
        }
      }
      out__.write(beta0);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 3;
      stan::model::assign(sigma2,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable sigma2");
      out__.write_free_lb(0, sigma2);
      Eigen::Matrix<local_scalar_t__,-1,1> rho_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      current_statement__ = 4;
      stan::model::assign(rho_raw,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(K),
        "assigning variable rho_raw");
      out__.write(rho_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "z", "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(N),
          static_cast<size_t>(P)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "beta0", "double",
        std::vector<size_t>{static_cast<size_t>(K), static_cast<size_t>(P)});
      current_statement__ = 3;
      context__.validate_dims("parameter initialization", "sigma2", "double",
        std::vector<size_t>{static_cast<size_t>(K)});
      current_statement__ = 4;
      context__.validate_dims("parameter initialization", "rho_raw",
        "double", std::vector<size_t>{static_cast<size_t>(K)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>> z =
        std::vector<std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>>(K,
          std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(N,
            Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__)));
      {
        std::vector<local_scalar_t__> z_flat__;
        current_statement__ = 1;
        z_flat__ = context__.vals_r("z");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            for (int sym3__ = 1; sym3__ <= K; ++sym3__) {
              stan::model::assign(z, z_flat__[(pos__ - 1)],
                "assigning variable z", stan::model::index_uni(sym3__),
                stan::model::index_uni(sym2__),
                stan::model::index_uni(sym1__));
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      out__.write(z);
      std::vector<Eigen::Matrix<local_scalar_t__,-1,1>> beta0 =
        std::vector<Eigen::Matrix<local_scalar_t__,-1,1>>(K,
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(P, DUMMY_VAR__));
      {
        std::vector<local_scalar_t__> beta0_flat__;
        current_statement__ = 2;
        beta0_flat__ = context__.vals_r("beta0");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
          for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
            stan::model::assign(beta0, beta0_flat__[(pos__ - 1)],
              "assigning variable beta0", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            pos__ = (pos__ + 1);
          }
        }
      }
      out__.write(beta0);
      Eigen::Matrix<local_scalar_t__,-1,1> sigma2 =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> sigma2_flat__;
        current_statement__ = 3;
        sigma2_flat__ = context__.vals_r("sigma2");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          stan::model::assign(sigma2, sigma2_flat__[(pos__ - 1)],
            "assigning variable sigma2", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, sigma2);
      Eigen::Matrix<local_scalar_t__,-1,1> rho_raw =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> rho_raw_flat__;
        current_statement__ = 4;
        rho_raw_flat__ = context__.vals_r("rho_raw");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          stan::model::assign(rho_raw, rho_raw_flat__[(pos__ - 1)],
            "assigning variable rho_raw", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write(rho_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"z", "beta0", "sigma2", "rho_raw"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"lo", "rho", "sigma_k", "beta"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"p_pred", "log_lik"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(K),
                                                 static_cast<size_t>(N),
                                                 static_cast<size_t>(P)},
                std::vector<size_t>{static_cast<size_t>(K),
                  static_cast<size_t>(P)},
                std::vector<size_t>{static_cast<size_t>(K)},
                std::vector<size_t>{static_cast<size_t>(K)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(K)},
             std::vector<size_t>{static_cast<size_t>(K)},
             std::vector<size_t>{static_cast<size_t>(K),
               static_cast<size_t>(N), static_cast<size_t>(P)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(T)},
             std::vector<size_t>{static_cast<size_t>(T)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= K; ++sym3__) {
          param_names__.emplace_back(std::string() + "z" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta0" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma2" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "rho_raw" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "lo");
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "rho" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "sigma_k" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= K; ++sym3__) {
            param_names__.emplace_back(std::string() + "beta" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "p_pred" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
        for (int sym3__ = 1; sym3__ <= K; ++sym3__) {
          param_names__.emplace_back(std::string() + "z" + '.' +
            std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
            std::to_string(sym1__));
        }
      }
    }
    for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
      for (int sym2__ = 1; sym2__ <= K; ++sym2__) {
        param_names__.emplace_back(std::string() + "beta0" + '.' +
          std::to_string(sym2__) + '.' + std::to_string(sym1__));
      }
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "sigma2" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
      param_names__.emplace_back(std::string() + "rho_raw" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "lo");
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "rho" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
        param_names__.emplace_back(std::string() + "sigma_k" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= P; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
          for (int sym3__ = 1; sym3__ <= K; ++sym3__) {
            param_names__.emplace_back(std::string() + "beta" + '.' +
              std::to_string(sym3__) + '.' + std::to_string(sym2__) + '.' +
              std::to_string(sym1__));
          }
        }
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "p_pred" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_lik" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"z\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "}}},\"block\":\"parameters\"},{\"name\":\"beta0\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "}},\"block\":\"parameters\"},{\"name\":\"sigma2\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"rho_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"lo\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"sigma_k\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "}}},\"block\":\"transformed_parameters\"},{\"name\":\"p_pred\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"z\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "}}},\"block\":\"parameters\"},{\"name\":\"beta0\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "}},\"block\":\"parameters\"},{\"name\":\"sigma2\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"rho_raw\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"parameters\"},{\"name\":\"lo\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"sigma_k\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(K) + "},\"block\":\"transformed_parameters\"},{\"name\":\"beta\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(K) + ",\"element_type\":{\"name\":\"array\",\"length\":" + std::to_string(N) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(P) + "}}},\"block\":\"transformed_parameters\"},{\"name\":\"p_pred\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"},{\"name\":\"log_lik\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(T) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((K * (N * P)) + (K * P)) + K) + K);
    const size_t num_transformed = emit_transformed_parameters * ((((1 + K) +
      K) + (K * (N * P))));
    const size_t num_gen_quantities = emit_generated_quantities * ((T + T));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = ((((K * (N * P)) + (K * P)) + K) + K);
    const size_t num_transformed = emit_transformed_parameters * ((((1 + K) +
      K) + (K * (N * P))));
    const size_t num_gen_quantities = emit_generated_quantities * ((T + T));
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = hierarchical_probit_bandit_model_namespace::hierarchical_probit_bandit_model;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return hierarchical_probit_bandit_model_namespace::profiles__;
}
#endif